let
    Source = Sql.Database("192.168.11.3", "QueueSystem"),
    dbo_nkevinDataAnalyticsBI = Source{[Schema="dbo",Item="nkevinDataAnalyticsBI"]}[Data],
    #"Convert CalloutTIme to text" = Table.TransformColumnTypes(dbo_nkevinDataAnalyticsBI,{{"CalloutTime", type text}, {"CustomerEnterTime", type text}}),
    #"Convert ResolveTime to tex" = Table.TransformColumnTypes(#"Convert CalloutTIme to text",{{"Resolvedtime", type text}}),
    #"Run Python script" = Python.Execute("# 'dataset' holds the input data for this script#(lf)allowed_users = [#(lf)    'FAITH.MOGAKA',#(lf)    'diana.maundu',#(lf)    'rosemary.kariuki',#(lf)    'RODAH.TIMBWA',#(lf)    'HARON.MAALU',#(lf)    'JOSEPHINE.ONDIMU',#(lf)    'HILLARY.MWAMBI',#(lf)    'KELVIN.MUSYOKA'#(lf)]#(lf)#(lf)dataset = dataset[dataset['Username'].isin(allowed_users)]#(lf)",[dataset=#"Convert ResolveTime to tex"]),
    #"Expanded Value" = Table.ExpandTableColumn(#"Run Python script", "Value", {"SystemGeneratedQueueNo", "DailyQueueNo", "DailyDate", "CustomerEnterTime", "CalloutTime", "CustomerWaitingTimeInMinutes", "CustomerBeingServedInMinutes", "WeekDate", "Monthdate", "Resolvedtime", "Username", "UserID", "SAFARICOM", "KCB", "SCBK", "KENGEN", "NBK", "KENYARE", "BRITAM", "KENOLKOBIL", "STANBIC", "SGL", "TPS", "EVERREADY", "SANLAM", "MUMIAS", "LIBERTY", "SASINI", "NBV", "LONGHORN", "JUBILEE", "BAT", "EABL", "WPP", "I AND M", "BANK OF KIGALI", "others", "Datetime", "Details", "counterno", "NAMES"}, {"SystemGeneratedQueueNo", "DailyQueueNo", "DailyDate", "CustomerEnterTime", "CalloutTime", "CustomerWaitingTimeInMinutes", "CustomerBeingServedInMinutes", "WeekDate", "Monthdate", "Resolvedtime", "Username", "UserID", "SAFARICOM", "KCB", "SCBK", "KENGEN", "NBK", "KENYARE", "BRITAM", "KENOLKOBIL", "STANBIC", "SGL", "TPS", "EVERREADY", "SANLAM", "MUMIAS", "LIBERTY", "SASINI", "NBV", "LONGHORN", "JUBILEE", "BAT", "EABL", "WPP", "I AND M", "BANK OF KIGALI", "others", "Datetime", "Details", "counterno", "NAMES"}),
    #"Convert Resolvt to time" = Table.TransformColumnTypes(#"Expanded Value",{{"Resolvedtime", type time}, {"CalloutTime", type time}, {"CustomerEnterTime", type time}, {"DailyDate", type datetime}, {"Datetime", type datetime}, {"EABL", Int64.Type}, {"BAT", Int64.Type}, {"JUBILEE", Int64.Type}, {"LONGHORN", Int64.Type}, {"NBV", Int64.Type}, {"SASINI", Int64.Type}, {"LIBERTY", Int64.Type}, {"MUMIAS", Int64.Type}, {"SANLAM", Int64.Type}, {"EVERREADY", Int64.Type}, {"TPS", Int64.Type}, {"SGL", Int64.Type}, {"STANBIC", Int64.Type}, {"KENOLKOBIL", Int64.Type}, {"BRITAM", Int64.Type}, {"KENYARE", Int64.Type}, {"NBK", Int64.Type}, {"KENGEN", Int64.Type}, {"SCBK", Int64.Type}, {"KCB", Int64.Type}, {"SAFARICOM", Int64.Type}, {"CustomerBeingServedInMinutes", Int64.Type}, {"CustomerWaitingTimeInMinutes", Int64.Type}, {"DailyQueueNo", Int64.Type}}),
    #"Removed Columns" = Table.RemoveColumns(#"Convert Resolvt to time",{"Name"})
in
    #"Removed Columns"